### PR TITLE
1.20.6 Update

### PR DESCRIPTION
**Pull request by MrBretze**

### CODE REVIEW

**Comment by magicus** [comment]
Perfect timing! Thank you @MrBretze. 

While I am not the owner of this project, I would recommend you to try and minimize spurious differences, like the extra newline in build.gradle and the indentation in gradle.properties. In general, patches that do not change irrelevant parts of the code is better accepted.

**Comment by MrBretze** [comment]
We need to modify build.gradle and gradle.properties to update to 1.20.6

**Comment by magicus** [comment]
Yes, I understand that. I was referring to the changes in whitespace and formatting that makes the diff larger than necessary.

**Comment by MrBretze** [comment]
For the moment i publied a compiled version here: https://github.com/MrBretze/debugStickSurvival/releases/tag/Fabric-1.20.6

**Comment by JustS-js** [comment]
Thanks for your service in my absence! I won't merge as i already implemented those fixes, but your help is appreciated

**Pull request closed without merging**
